<h2>Extrow data</h2>
<p>All operations have been done. You can grab your data in personal cabinet.</p>
<?php $link = $this->serverUrl($this->url('settings/default', ['action' => 'download'])); ?>
<p><a href="<?php echo $link ?>">Get!</a></p>
<p><?php echo $link ?></p>
<hr>
<p>Any questions?</p>
<table border="0" cellpadding="0" cellspacing="0">
    <tr>
        <td style="padding-right: 5px">Send mail:</td>
        <td><a href="mailto:someone@example.com?Subject=Email%20confirmation">Versover Team</a></td>
    </tr>
    <tr>
        <td style="padding-right: 5px">Website:</td>
        <td><a href="http://versover.com" target="_blank">Versover</a></td>
    </tr>
    <tr>
        <td style="padding-right: 5px">Skype:</td>
        <td><a href="skype:versover?chat">Versover</a></td>
    </tr>
</table>
<p>Regards, Versover team.</p>