<?php
$title = 'Get Started';
$this->headTitle($title);
?>
<div class="row">
    <div class="col col-md-12">
        <div class="container">
            <h2 class="text-center">
                <a href="<?php echo $this->url('get-started'); ?>">Select source</a>
            </h2>

            <div class="well source-list">
                <ul class="list-unstyled list-inline">
                    <li><a href="#/ebay" class="making-call">eBay</a></li>
                    <li>Amazon</li>
                    <li>...</li>
                </ul>
            </div>

            <div class="form-place hide">
                <!-- Form here -->
            </div>
        </div>
    </div>
</div>
