<?php
$title = 'Get Started';
$this->headTitle($title);
?>
<div class="row">
    <div class="col col-md-12">
        <div class="container">
            <h2>Select </h2>
            <ul class="nav nav-tabs">
                <li class="active"><a data-toggle="tab" href="#ebay">eBay</a></li>
                <li><a href="#amazon" class="disabled">Amazon</a></li>
                <li><a href="#" class="disabled">...</a></li>
            </ul>

            <div class="tab-content">
                <div id="ebay" class="tab-pane fade in active">
                    <h3>eBay</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                </div>
                <div id="amazon" class="tab-pane fade">
                    <h3>Amazon</h3>
                    <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                </div>
                <div id="menu3" class="tab-pane fade">
                    <h3>Menu 2</h3>
                    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam.</p>
                </div>
            </div>
        </div>
    </div>
</div>
