<h2>Reset password</h2>
<p>You have received this email because you initiated to reset your password with us. To continue with the process, please click the link below:</p>
<?php $link = $this->serverUrl($this->url('zfcuser/resetpassword', ['userId' => $this->record->getUserId(), 'token' => $this->record->getRequestKey()])); ?>
<p><a href="<?php echo $link ?>">Reset</a></p>
<p>or copy the link into your browser</p>
<p><?php echo $link ?></p>
<hr>
<p>Any questions?</p>
<table border="0" cellpadding="0" cellspacing="0">
    <tr>
        <td style="padding-right: 5px">Send mail:</td>
        <td><a href="mailto:someone@example.com?Subject=Email%20confirmation">Versover Team</a></td>
    </tr>
    <tr>
        <td style="padding-right: 5px">Website:</td>
        <td><a href="http://versover.com" target="_blank">Versover</a></td>
    </tr>
    <tr>
        <td style="padding-right: 5px">Skype:</td>
        <td><a href="skype:versover?chat">Versover</a></td>
    </tr>
</table>
<p>Regards, Versover team.</p>