<h2>Set your account password</h2>
<p>
    An account was created with this email address.<br/>
    Please click on the following link to set your account password.
</p>

<?php $link = $this->serverUrl() . $this->url('zfcuser/set_password', ['userId' => $user->getId(), 'token' => $registrationRecord->getToken()]); ?>
<a href="<?php echo $link ?>"><?php echo $link; ?></a>

<hr>

<p>Any questions?</p>
<table border="0" cellpadding="0" cellspacing="0">
    <tr>
        <td style="padding-right: 5px">Send mail:</td>
        <td><a href="mailto:someone@example.com?Subject=Email%20confirmation">Versover Team</a></td>
    </tr>
    <tr>
        <td style="padding-right: 5px">Website:</td>
        <td><a href="http://versover.com" target="_blank">Versover</a></td>
    </tr>
    <tr>
        <td style="padding-right: 5px">Skype:</td>
        <td><a href="skype:versover?chat">Versover</a></td>
    </tr>
</table>
<p>Regards, Versover team.</p>
