<h1 class="text-center form-header"><?php echo $this->translate('Register'); ?></h1>

<?php
if (!$this->enableRegistration) {
    echo 'Registration is disabled';
    return;
}

$title = 'Register';
$this->headTitle($title);

$placeholders = ['Email', 'Password', 'Password Verify'];
$counter = 0;

$form = $this->registerForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form');
?>

<?php echo $this->form()->openTag($form) ?>

    <?php foreach ($form as $element): ?>
        <?php if (!$element instanceof Zend\Form\Element\Button): ?>
            <?php //echo $this->formLabel($element) ?>
        <?php endif ?>
        <?php if ($element instanceof Zend\Form\Element\Button): ?>
            <?php echo $this->formButton($element->setAttribute('class', 'btn btn-primary btn-lg btn-block submit-btn')) ?>
        <?php elseif ($element instanceof Zend\Form\Element\Captcha): ?>
            <?php echo $this->formCaptcha($element) . $this->formElementErrors($element) ?>
        <?php else: ?>
            <?php if ($placeholders[$counter] == 'Email') : ?>
                <?php echo $this->formInput($element->setAttributes([
                        'class'         => 'form-control',
                        'placeholder'   => $placeholders[$counter],
                        'type'        => 'email',
                        'autocomplete'  => 'off',
                        'required'      => true,
                    ])) . $this->formElementErrors($element) ?>
            <?php else : ?>
                <?php echo $this->formInput($element->setAttributes([
                        'class'         => 'form-control',
                        'placeholder'   => $placeholders[$counter],
                        'autocomplete'  => 'off',
                        'required'      => true,
                    ])) . $this->formElementErrors($element) ?>
            <?php endif ?>
        <?php endif ?>

        <?php $counter++ ?>

    <?php endforeach ?>

    <?php if ($this->redirect): ?>
        <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>">
    <?php endif ?>
<?php echo $this->form()->closeTag() ?>
<p><?php echo $this->translate('Already registered?'); ?> <a href="<?php echo $this->url('zfcuser/login') ?>"><?php echo $this->translate('Sign in!'); ?></a></p>
