<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Extrow'))->setSeparator(' &bull; ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('/css/app.css'))
        ; ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile(('//oss.maxcdn.com/respond/1.4.2/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile(('//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class="container-fluid">
            <!-- main nav -->
            <div class="navbar navbar-inverse">
                <!--a href="<?php echo $this->url('zfcuser/login'); ?>" class="btn btn-lg sign-in-btn"><i class="fa fa-2x fa-sign-in"></i> Sign In</a-->
                <a href="<?php echo $this->url('zfcuser/login'); ?>" class="btn btn-lg sign-in-btn" data-toggle="tooltip" data-placement="bottom" title="Sign In"><i class="fa fa-2x fa-sign-in"></i></a>
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <h1 class="logo"><a class="navbar-brand" href="<?php echo $this->url('home'); ?>">Extrow</a></h1>
                    </div>
                    <div class="navbar-collapse collapse navbar-responsive-collapse">
                        <?php echo $this->navigation('navigation')->menu()->setULClass('nav navbar-nav navbar-right'); ?>
                    </div>
                </div>
            </div><!-- /main nav -->
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        <footer>
            <p class="text-center">&copy; <?php echo date('Y') ?> by <a href="http://versover.com" target="_blank">Versover</a> <?php echo $this->translate('All rights reserved.') ?></p>
        </footer>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
        <?php
        $script = $this->inlineScript();
        $script
            ->appendFile($this->basePath() . '/js/app.js');

        echo $script;
        ?>
    </body>
</html>
