<?php
$socialSignIn = true;

if ($this->options->getSocialLoginOnly() == false) : ?>
    <div class="container">
        <div class="row">
            <div class="col col-md-6 col-md-offset-3">
                <div class="auth-box">
                    <div class="auth">
                        <?php echo $this->zfcUserLogin; ?>
                    </div>

                    <div class="social-auth">
                        <?php
                        foreach ($this->options->getEnabledProviders() as $provider) {
                            if ($socialSignIn) {
                                $socialSignIn = false;
                            }

                            //echo $this->socialSignInButton($provider, $this->redirect);

                            if ($provider == 'google') {
                                echo '<a href="/user/login/google"><i class="fa fa-4x fa-google-plus-square"></i></a>';
                            }

                            if ($provider == 'facebook') {
                                echo '<a href="/user/login/facebook"><i class="fa fa-4x fa-facebook-square"></i></a>';
                            }
                        }
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
