<?php
$title = 'Home';
$this->headTitle($title);
?>
<div class="row">
    <div class="col col-md-12">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                    <div class="item active">
                        <img src="http://placehold.it/1920x600/16a085/ffffff">
                        <div class="carousel-caption">
                            <h3>Headline</h3>
                            <p>
                                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
                                tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. Lorem
                                ipsum dolor sit amet, consetetur sadipscing elitr.</p>
                        </div>
                    </div>
                    <!-- End Item -->
                    <div class="item">
                        <img src="http://placehold.it/1920x600/e67e22/ffffff">
                        <div class="carousel-caption">
                            <h3>Headline</h3>
                            <p>
                                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
                                tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. Lorem
                                ipsum dolor sit amet, consetetur sadipscing elitr.</p>
                        </div>
                    </div>
                    <!-- End Item -->
                    <div class="item">
                        <img src="http://placehold.it/1920x600/2980b9/ffffff">
                        <div class="carousel-caption">
                            <h3>Headline</h3>
                            <p>
                                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
                                tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. Lorem
                                ipsum dolor sit amet, consetetur sadipscing elitr.</p>
                        </div>
                    </div>
                    <!-- End Item -->
                    <div class="item">
                        <img src="http://placehold.it/1920x600/8e44ad/ffffff">
                        <div class="carousel-caption">
                            <h3>Headline</h3>
                            <p>
                                Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
                                tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. Lorem
                                ipsum dolor sit amet, consetetur sadipscing elitr.</p>
                        </div>
                    </div>
                    <!-- End Item -->
                </div>
                <!-- End Carousel Inner -->
                <ul class="nav nav-pills nav-justified">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"><a href="#">Slide<small>Lorem ipsum dolor sit</small></a></li>
                    <li data-target="#myCarousel" data-slide-to="1"><a href="#">Slide<small>Lorem ipsum dolor sit</small></a></li>
                    <li data-target="#myCarousel" data-slide-to="2"><a href="#">Slide<small>Lorem ipsum dolor sit</small></a></li>
                    <li data-target="#myCarousel" data-slide-to="3"><a href="#">Slide<small>Lorem ipsum dolor sit</small></a></li>
                </ul>
            </div>
            <!-- End Carousel -->
    </div>
</div>
